services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 4300:4300
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=spinova-api-node